import json
import subprocess
from pathlib import Path

from agentflow.session_store import SessionStore


class HerdrProvisionError(RuntimeError):
    pass


class HerdrProvisioner:
    def __init__(self, root: Path) -> None:
        self.root = root

    def _run(self, *args):
        try:
            result = subprocess.run(  # noqa: S603 - Herdr arguments are generated by the adapter
                ["herdr", *args],  # noqa: S607 - executable and arguments are controlled by Agentflow
                cwd=self.root,
                text=True,
                capture_output=True,
                check=True,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            raise HerdrProvisionError(str(exc)) from exc
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise HerdrProvisionError(f"Herdr returned non-JSON output: {result.stdout}") from exc

    def provision(self):
        store = SessionStore(self.root / "runtime/sessions.json")
        current = store.load()
        panes = self._run("pane", "list")["result"]["panes"]
        agents = self._run("agent", "list")["result"]["agents"]
        sessions = {}
        used_panes = set()
        for role in ("developer", "tester", "reviewer"):
            saved = current.get(role) or ""
            saved_pane_id = saved.removeprefix("herdr:pane:")
            named = next((a for a in agents if a.get("name") == role), None)
            pane = next(
                (
                    p
                    for p in panes
                    if p.get("pane_id") == (named or {}).get("pane_id")
                    and p.get("pane_id") not in used_panes
                ),
                None,
            )
            if pane is None:
                pane = next(
                    (
                        p
                        for p in panes
                        if p.get("pane_id") == saved_pane_id and saved_pane_id not in used_panes
                    ),
                    None,
                )
            if pane is None:
                tab = self._run(
                    "tab", "create", "--cwd", str(self.root), "--label", role, "--no-focus"
                )["result"]
                pane = tab.get("pane") or tab.get("root_pane") or tab.get("panes", [{}])[0]
                pane_id = pane.get("pane_id")
                if not pane_id:
                    raise HerdrProvisionError(f"Could not find pane ID in tab create result: {tab}")
                self._run(
                    "agent",
                    "start",
                    role,
                    "--kind",
                    "codex",
                    "--pane",
                    pane_id,
                    "--timeout",
                    "120000",
                )
                panes = self._run("pane", "list")["result"]["panes"]
                pane = next((p for p in panes if p.get("pane_id") == pane_id), None)
            if not pane or not pane.get("pane_id"):
                raise HerdrProvisionError(f"Herdr did not report a pane for {role}")
            # Herdr's installed CLI exposes the pane identity reliably; its
            # agent-session identity report requires an agent-supplied source
            # token, so persist the pane handle for Herdr prompt routing.
            sessions[role] = f"herdr:pane:{pane['pane_id']}"
            used_panes.add(pane["pane_id"])
        store.save(sessions)
        return sessions
