# Generated by Django 5.2.17 on 2026-09-16 00:19

import django.db.models.deletion
from django.db import migrations, models

# Ruff's RUF012 and D101 rules do not understand Django migration metadata.
# ruff: noqa: D101, RUF012


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["surname", "first_name"],
                "indexes": [models.Index(fields=["surname", "first_name"], name="actor_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["surname", "first_name"],
                "indexes": [
                    models.Index(fields=["surname", "first_name"], name="director_name_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="language_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Screenplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["surname", "first_name"],
                "indexes": [
                    models.Index(fields=["surname", "first_name"], name="screenplay_name_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="studio_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("G", "G"),
                            ("PG", "PG"),
                            ("PG-13", "PG-13"),
                            ("R", "R"),
                            ("NC-17", "NC-17"),
                        ],
                        max_length=5,
                    ),
                ),
                ("duration_in_minutes", models.PositiveSmallIntegerField()),
                ("short_description", models.TextField(blank=True)),
                ("full_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="published", max_length=50)),
                (
                    "actors",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.actor"),
                ),
                (
                    "countries",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.country"),
                ),
                (
                    "directors",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.director"),
                ),
                (
                    "genres",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.genre"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="core.language",
                    ),
                ),
                (
                    "screenplays",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.screenplay"),
                ),
                (
                    "studios",
                    models.ManyToManyField(blank=True, related_name="movies", to="core.studio"),
                ),
            ],
            options={
                "ordering": ["-year", "title"],
                "indexes": [
                    models.Index(fields=["title"], name="movie_title_idx"),
                    models.Index(fields=["year"], name="movie_year_idx"),
                    models.Index(fields=["rating"], name="movie_rating_idx"),
                    models.Index(fields=["language", "year"], name="movie_language_year_idx"),
                ],
            },
        ),
    ]
